! -----------------------------------------------------------------------------------
! Test Description: Multiple Analysis, view and up axis
!
!
!
!
!
! -----------------------------------------------------------------------------------

!-----------------------
! Delete local variables
!-----------------------
if condition=(eval(db_of_type_exists(".adams_auto_animate.*", "variable")))
   var del var=.adams_auto_animate.*
end

!----------
! Run Macro
!----------
auto_animate &
	analyses=run_001, run_002, run_003 &
	view=iso &
	up_axis=X_neg
	
